export {HomePage} from './HomePage'
export {Login} from './Login'
export {Register} from './Register'
export {Customer} from './Customer'
export {Info} from './Info'
export {Historico} from './Historico'
export {Admin} from './Admin'
export {NotFoundPage} from './NotFoundPage'